# Generated by Django 2.2.13 on 2021-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactlist_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='Mobileno',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
